[workspace]
resolver = "2"
members = ["radixox-common", "radixox", "radixox-server", "oxidart"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Joshua"]
license = "MIT"

[workspace.dependencies]
radixox-common = { path = "radixox-common" }
monoio = { version = "0.2.4", features = ["iouring"] }
prost = "0.14.3"
serde = { version = "1.0.228", features = ["derive"] }
bytes = { version = "1", features = ["serde"] }
slotmap = "1.1.1"
oxidart = { path = "oxidart", features = ["monoio", "regex"] }
smallvec = "1.15.1"
